#!/bin/bash

# Final Deployment Script for Google Cloud Run
# THEO Clothing Inventory Management System

echo "🚀 THEO Inventory - Final Cloud Run Deployment"
echo "=============================================="

# Configuration
PROJECT_ID="spry-scope-473614-v8"
FIREBASE_PROJECT_ID="inventory-3098f"
SERVICE_NAME="theo-inventory"
REGION="us-central1"
FIREBASE_STORAGE_BUCKET="inventory-3098f.appspot.com"

echo "📋 Configuration:"
echo "  Project ID: $PROJECT_ID"
echo "  Firebase Project: $FIREBASE_PROJECT_ID"
echo "  Service Name: $SERVICE_NAME"
echo "  Region: $REGION"
echo "  Storage Bucket: $FIREBASE_STORAGE_BUCKET"
echo ""

echo "✅ Container successfully built and pushed!"
echo "✅ Image: gcr.io/$PROJECT_ID/$SERVICE_NAME"
echo ""

echo "🔧 Manual Deployment Steps:"
echo ""
echo "1. Go to Google Cloud Console:"
echo "   https://console.cloud.google.com/run"
echo ""
echo "2. Click 'Create Service'"
echo ""
echo "3. Configure the service:"
echo "   - Service name: $SERVICE_NAME"
echo "   - Region: $REGION"
echo "   - Container image URL: gcr.io/$PROJECT_ID/$SERVICE_NAME"
echo "   - Allow unauthenticated invocations: Yes"
echo ""
echo "4. Advanced settings:"
echo "   - Memory: 1 GiB"
echo "   - CPU: 1"
echo "   - Min instances: 0"
echo "   - Max instances: 10"
echo "   - Port: 8000"
echo "   - Timeout: 300 seconds"
echo "   - Concurrency: 80"
echo ""
echo "5. Environment variables:"
echo "   - FLASK_ENV=production"
echo "   - FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID"
echo "   - FIREBASE_STORAGE_BUCKET=$FIREBASE_STORAGE_BUCKET"
echo "   - SESSION_COOKIE_SECURE=true"
echo ""
echo "6. Click 'Create'"
echo ""
echo "🎉 After deployment, your app will be available at:"
echo "   https://$SERVICE_NAME-$PROJECT_ID.a.run.app"
echo ""
echo "🔍 Health check:"
echo "   https://$SERVICE_NAME-$PROJECT_ID.a.run.app/health"
echo ""
echo "💰 Estimated monthly cost: $0-10 (pay-per-use pricing)"
echo "🚀 Your inventory management system will run 24/7 on Google Cloud Run!"
